### PR TITLE
add help screen to admin list table

### LINKED ISSUE #275: Add help tab content for admin page
AS adds a menu item to the *Tools* admin page, but doesn't provide any intro or background about why this menu item exists, and what exactly the information is that it's displaying.

This comes up as an issue from time-to-time, e.g. https://github.com/woocommerce/woocommerce/pull/23064

We can address this by [adding a help tab](https://codex.wordpress.org/Class_Reference/WP_Screen/add_help_tab) to provide this information.

### PR DESCRIPTION
**Pull request by rrennick**
Closes #275 

This PR adds a basic help screen to the Tools -> Scheduled Actions screen.

### CODE REVIEW

**Comment by rrennick** [comment]
@thenbrent Can you review the text and suggest any improvements or changes?

**Comment by thenbrent** [comment]
@rrennick finally getting to this one! It looks like `ActionScheduler_AdminHelp` wasn't committed.  :)

**Comment by rrennick** [comment]
> It looks like ActionScheduler_AdminHelp wasn't committed. :)

Fixed.

**Comment by thenbrent** [comment]
LGTM. 👍

**Pull request merged**
