### PR TITLE
Better handling for malformed args

### PR DESCRIPTION
**Pull request by JPry**
Helps with an issue brought up in #151.

### CODE REVIEW

**Comment by thenbrent** [comment]
@JPry I think AS should throw an exception instead of defaulting to empty args. Empty args could potentially let things continue without any notice or logged issue, when there was an error that should be addressed (and could potentially lead to things like missed payments etc.).

**Comment by thenbrent** [comment]
> what we do with any thrown exceptions

Definitely a valid concern.

I think that needs to be treated as a separate issue to how malformed args are handled though. Largely because there are many different ways these malformed args can occur, or be encountered, and the ideal solutions to most of those (the code responsible for scheduling the action handling it based on its knowledge of the what the action is/does) is outside of our control.

> This is because ActionScheduler_ListTable::prepare_items() just ignores Exceptions:

That's a good example of a case, and also something that should be handled outside this PR. Doing it as part of this PR would slow down the better handling of malformed args because I think `ActionScheduler_ListTable::prepare_items()` should really be handling _all_ exceptions better, not just any custom AS exceptions, or known exceptions. Ideally, `ActionScheduler_ListTable` would print something about the exception in the table (or not catch and ignore the exception at least, to let PHP do that for us). But that is more around an issue with the list table's handling of exception than it is with handling for malformed args.

**Comment by thenbrent** [comment]
I should have also said above, definitely 👍 for using custom exceptions for this (and other) exceptions. :)

**Comment by JPry** [comment]
> definitely 👍 for using custom exceptions for this (and other) exceptions.

This brings to mind something I've been thinking about but haven't yet written up into a proper issue. I was thinking that it would ultimately be good to move Action Scheduler into using a namespace and implementing a PSR-4 structure.

In order to accomplish this without taking time away from other more important things, this could be done more incrementally. For example, in this case custom exceptions could be added in the proper Structure while maintaining existing structure for everything else. Then we can gradually move everything over. I'll try to get this written up into a proper issue tomorrow with more fleshed out details.

**Comment by JPry** [comment]
@thenbrent I've pushed some new commits that start to implement the changes I mentioned, without going way out of scope for this PR (in my opinion):

* Added the `src/` directory. This will be the root of the `Prospress\ActionScheduler` namespace.
* Added a PSR-4 autoloader. This keeps us from needing to rely on composer, and we'll be able to handle the updated Namespace going forward.
* Created a custom Exception interface. All of our custom exceptions will implement this type, and it will allow us to start catching exceptions that are unique to Action Scheduler.
* Created the first custom exception, `InvalidAction`. This exception currently has a method that will return a new exception object when an action ID has invalid arguments. We can add more methods over time as needed, as well as different types of exceptions.

This admittedly does go a bit beyond what we're looking to accomplish here, but I think it's within reason considering my prior comment.

Let me know what you think in general, and feel free to review when you're able 🙂

**Comment by JPry** [comment]
@thenbrent I've amended the commits for this PR to **only** include the new Exceptions. The existing autoloader method has been updated to handle locating these files. Additionally, they are located in the existing `classes/` directory instead of a new `src/` directory.

**Comment by JPry** [comment]
@thenbrent I've updated this PR so that the changes fit better with the existing codebase structure.

**Comment by thenbrent** [comment]
LGTM. 👍

**Pull request merged**
