### PR TITLE
Identify in-use data store

### LINKED ISSUE #568: Identify in-use data store
Is there a non-programmatic way of determining which data store is in-use?

By non-programmatic, I mean not getting the class name of `ActionScheduler_Store::instance()`. This would be helpful to someone troubleshooting or performing an audit that doesn't have code-level access, or in a case where someone would rather not making code changes on a production environment.

There are a few options I see for making this (and other technical info) available:
- add a _Technical Details_ or _System_ tab to Help drawer on Tools > Scheduled Actions page
- add to output of `wp action-scheduler info` CLI command, once merged (#279)
- add to WooCommerce System Status table

### PR DESCRIPTION
**Pull request by crstauf**
Closes #568.

### CODE REVIEW

**Comment by rrennick** [comment]
@crstauf Nice suggestion :) 

In a planning meeting several months ago we discussed the type of info to be included in the help tab and decided to limit the technical information to the version number. If you could update the PR to remove the help tab change I'll have time later this week to review.

**Comment by crstauf** [comment]
> update the PR to remove the help tab change

@rrennick Removed.

**Review by rrennick — APPROVED** [review]
@crstauf Nice addition.

**Comment by crstauf** [comment]
@rrennick This was merged into `master` rather than `version_3_2_0`... confirming that's intentional?

**Comment by rrennick** [comment]
@crstauf Thanks, I merged `master` into 3_2_0.

**Pull request merged**
