### PR TITLE
update: Added Action scheduler completed action hook

### PR DESCRIPTION
**Pull request by ManiruzzamanAkash**
- [Enhancement] Added Action scheduler completed action hook.

I think added a simple hook when completed an action would solve many use cases pretty much simpler. And as there is no normal way to detect if actions is completed, this hook could be integrated.

Discussion in #729 

And for reference, same way, there is already a hook for `Canceled action` on `line-460`
```php
do_action( 'action_scheduler_canceled_action', $action_id );
```

So, it would be awesome if the new hook is integrated for completed action.

### Changelog 

> Enhancement - Add new action hook `action_scheduler_completed_action`.

### CODE REVIEW

**Review by barryhughes — CHANGES_REQUESTED** [review]
Thanks!

Ideally, the WP Post store should also be updated with the same hook. It would also be worth [documenting the hook](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#4-hooks-actions-and-filters).

**Comment by ManiruzzamanAkash** [comment]
@barryhughes Thanks for your feedback.
I've not added the docblock to keep the consistency with other similar hooks(cancel). However, added the docblock.

**Comment by barryhughes** [comment]
Thanks!

Some of the older code does not meet our current standards, but where possible for new code we do try to implement these things.

Note that we would still want the [WP Post Store](https://github.com/woocommerce/action-scheduler/blob/3.4.1/classes/data-stores/ActionScheduler_wpPostStore.php) to be updated with the same functionality, to avoid problems arising from a discrepancy between the two.

**Review by barryhughes — APPROVED** [review]
Thanks!

**Pull request merged**
