### PR TITLE
Add deltas to equals assertion to prevent false failures

### PR DESCRIPTION
**Pull request by crstauf**

### CODE REVIEW

**Comment by rrennick** [comment]
@crstauf You can also do deltas in 5.X/6.X versions of PHPUnit with

```$this->assertEquals( $now1->getTimestamp(), $now2->getTimestamp(), '', 2 );```

**Comment by crstauf** [comment]
> You can also do deltas in 5.X/6.X version of PHPUnit

Thanks, @rrennick! Implemented in 99d8ff6.

**Review by rrennick — APPROVED** [review]
@crstauf Looks great. Thanks for the PR.

**Comment by crstauf** [comment]
Welcome! :bow:

**Pull request merged**
