### PR TITLE
Timezone fixes

### PR DESCRIPTION
**Pull request by thenbrent**
This is the first draft of a PR to ensure we use UTC and `post_date_gmt` to avoid issues relating to daylight savings time, changes to the site's timezone and 3rd party code calling `date_default_timezone_set()`.

### CODE REVIEW

**Comment by thenbrent** [comment]
@mattallan I've fixed up the tests on this now with SHA: 4aac28e30994d3b2e

I also updated all the tests to use `UTC` explicitly before realising the above was the required fix (see SHA: 5007272a4ec6a84a5).

Finally, I had to update the WP versions to be 4.3+ because the WP Testing framework isn't backward compatible for version <= 4.3 (see SHA: 2d46c69421e) and PHP versions (with SHA: ) because PHP 5.2 is no longer supported (SHA: e383dc109).

This PR is now ready for much closer review.

Even though it will be redundant when/if we migrate AS to use custom tables, it's possibly still worth reviewing and merging to get out with Subscriptions prior to then.

**Comment by mattallan** [comment]
There are still some timezone issues in the action scheduler which I think are stemming from the use of `new DateTime();` especially when we fire off a scheduled action, and then check if original scheduled time is still in the future (to see if the AS should reschedule at the original time)

Stepping through the code..
After the action is run, see if we need to reschedule it. 

```
protected function schedule_next_instance( ActionScheduler_Action $action ) {
	$next = $action->get_schedule()->next( new DateTime() );
	if ( $next ) {
		$this->store->save_action( $action, $next );
	}
}
```

[`next()`](https://github.com/Prospress/action-scheduler/blob/master/classes/ActionScheduler_SimpleSchedule.php#L18) will return null if the next scheduled date is not in the future.

This is where the issue is. It shouldn't return a next date that is in the future, so now going to where the scheduled date is stored ([here](https://github.com/Prospress/action-scheduler/blob/master/classes/ActionScheduler_ActionFactory.php#L15))

```
public function single( $hook, $args = array(), $when = NULL, $group = '' ) {
	$date = ActionScheduler::get_datetime_object( $when );
	$schedule = new ActionScheduler_SimpleSchedule( $date );
	$action = new ActionScheduler_Action( $hook, $args, $schedule, $group );
	return $this->store( $action );
}
```

The [`get_date_object()`](https://github.com/Prospress/action-scheduler/blob/master/classes/ActionScheduler.php#L31) function looks like:

```
public static function get_datetime_object( $when ) {
		$when = empty($when) ? time() : $when;
		if ( is_object($when) && $when instanceof DateTime ) {
			$date = $when;
		} elseif ( is_numeric( $when ) ) {
			$date = new DateTime( '@'.$when );
		} else {
			$date = new DateTime( $when );
		}
		return $date;
	}
```

@thenbrent: following your recent changes, should we adding `new DateTimeZone('UTC')` to these DateTime uses?

I was using https://gimme.subscription.beer/AS_Timezones to test and replicate the bug.

**Comment by thenbrent** [comment]
> @thenbrent: following your recent changes, should we adding new DateTimeZone('UTC') to these DateTime uses?

Yeah, good catch. I'm not sure why I didn't think to update all `new DateTime()` calls in AS itself when I did that in all the tests with SHA: 5007272a4ec6a84

I think I'll introduce a new `as_get_datetime()` method to use instead of having to write `new DateTime(null, new DateTimeZone('UTC'))` everywhere.

I can also then use that single method to test the impact of `date_default_timezone_set()` on instances of `DateTime()`.

**Comment by thenbrent** [comment]
@mattallan this is ready for for review again now. I've introduced a new `as_get_datetime_object()` function to use everywhere a `DateTime` instance is used. This ensures we always have objects using the `UTC` timezone, unless a different timezone is explicitly specified.

I've also added some tests for that method and deprecated the existing `get_datetime_object()` method in favour of this one.

Finally, I've added a hack to run all tests under 3 different PHP timezone conditions to try to surface these kinds of issues in the unit tests.

I'll give it a closer review again next week too as it changes so much, don't rush to pull the trigger on it!

**Comment by mattallan** [comment]
I've just finished looking over all these changes and nothing problematic stands out and i also agree with all the changes :)

I'm going to create a few gimme sites running this patch to see if i can replicate the same issue from https://github.com/Prospress/action-scheduler/pull/43#issuecomment-218951166 (new patches should definitely fix it) and also a few other issues i've come across on other peoples sites :+1:

> I'll give it a closer review again next week too as it changes so much

Sounds good.

---

 - [ ] schedule action in `'Brazil/East'` timezone ( UTC-5 ) and keep that timezone at renewal as well
 - [ ] schedule action in `'Brazil/East'` timezone, change site to UTC and wait for renewal to trigger
 - [ ] schedule action in `UTC`, let renewal trigger in `'Brazil/East'`
 - [ ] change store's time in between renewals
 - [ ] Standard tests (no funny business)

**Comment by thenbrent** [comment]
I've just merged in the latest from `bleeding_branch` with SHA: 273e41e7cfead6cb16d7 as there were some merge conflicts (from #56) that needed to be addressed.

**Comment by james-allan** [comment]
Ran a couple of tests today to replicate the issue with changing the site's timezone (the WP settings timezone). I replicated the original issue on `bleeding_branch` following these steps: 

1. Purchase a subscription in UTC + 0 (https://cloudup.com/cka1sRl80zs)
2. I moved the next payment date forward to avoid waiting a day
3. Set the sites timezone to be UTC + 1. _(Sites which have selected a state like Melbourne rather than a timezone `UTC +x` will automatically get updated to daylight saving times and so will not have to do this manually)_
4 waited .. 
- Renewal order triggered 1 hour early and scheduled 2 actions 
 1. 1 hour in the future 👎 
 2. 1 day in the future (it's a daily sub) 👍 
5. Second renewal triggers 1 hour after the first.

Switched to this branch:

1. Followed steps **1->4** from above.
2. Renewal order triggered on time, no extra actions and no duplicated renewals 🎉 

------------------------------

Subscription which duplicated: https://gimme.subscription.beer/James-timezone/wp-admin/post.php?post=14&action=edit
Subscription which was fine: https://gimme.subscription.beer/James-timezone/wp-admin/post.php?post=21&action=edit

I believe it is [this change](https://github.com/Prospress/action-scheduler/pull/43/files#diff-ffba07a4fcd3281ec1f31d812c761966R402) which fixed this bug. Previously the actions would be claimed using the sites timezone and the action's `post_date`. If a scheduled action was scheduled in UTC + 0 and claimed in UTC + 1 it would technically be claimed 1 hour early. The scheduled action's `post_date_gmt` would then be compared against the current GMT time [(here)](https://github.com/Prospress/action-scheduler/pull/43/files#diff-124f8a880d3f05780897f2a840cf4274L20) and because it would be 1 hour in the future, it would reschedule the action. 

I also had a look through the code at the end of last week and it LGTM.

**Comment by thenbrent** [comment]
> I believe it is this change which fixed this bug.

Yeah it is. That's the single most important change in this PR, which now has a lot of other timezone patches squeezed in (which only cause issues under more unusual circumstances, like sites with `date_default_timezone_set()` being called). 👍 

All sounds promising. We'll just wait to hear if @mattallan was able to reproduce the other timezone issue on `bleeding_branch`, then I think this will be ready to merge and 🚀

**Comment by thenbrent** [comment]
Just adding a copy of @mattallan's notes on testing in Slack for posterity:

> i’ve been printing out a number of error logs and I can confirm that it’s not being scheduled by the action-scheduler, so we can merge the PR in now. I think the second renewal that i’ve been able to replicate is coming from within Subscriptions (i.e. subscriptions thinks the next payment date already stored on the subscription is in the future, so it just uses that date and scheduled the next payment date for 3hrs in the future again)

**Pull request merged**
