### PR TITLE
Fix system status export formatting

### PR DESCRIPTION
**Pull request by thenbrent**
For background see: https://github.com/Prospress/action-scheduler/pull/243#issuecomment-470748600

### CODE REVIEW

**Comment by crstauf** [comment]
@thenbrent Not sure if intentional, but want to point out this was not merged into `master`, but rather into `issue_222`. `master` continues to have the issue with only the oldest scheduled date showing in the raw system status.

**Comment by thenbrent** [comment]
Ah I didn't see that, thanks for pointing it out @crstauf 🙇

**Comment by crstauf** [comment]
@thenbrent Just checking to see if this merge was corrected?

**Comment by JPry** [comment]
@crstauf It looks like `master` does have these changes:

https://github.com/Prospress/action-scheduler/blob/076630e7a0d5d1fb47f0d77c095e0fb86b99842a/classes/ActionScheduler_wcSystemStatus.php#L97-L124

**Pull request merged**
