### PR TITLE
PHPCS: `classes/data-stores/ActionScheduler_wpPostStore_PostTypeRegistrar.php`

### PR DESCRIPTION
**Pull request by crstauf**

### CODE REVIEW

**Comment by crstauf** [comment]
@barryhughes Composer failure.

**Comment by crstauf** [comment]
@barryhughes Composer failure.

**Comment by crstauf** [comment]
@barryhughes Composer failure.

**Review by barryhughes — APPROVED** [review]

**Comment by barryhughes** [comment]
Closing/reopening (sometimes clears CI issues).

**Pull request merged**
