### PR TITLE
Unschedule action only by hook name

### LINKED ISSUE #417: Unschedule action only by hook name
The [documentation for `as_unschedule_action()`](https://github.com/woocommerce/action-scheduler/blob/master/docs/api.md#function-reference--as_unschedule_action) indicates that only the hook name is required, but in my quick test, the other arguments are needed as well.

Is the documentation incorrect, or should actions be able to be unscheduled with only the hook name?

### PR DESCRIPTION
**Pull request by crstauf**
Fixes #417.

### CODE REVIEW

**Comment by leewillis77** [comment]
See my comment here: https://github.com/woocommerce/action-scheduler/issues/417#issuecomment-593938555

I think this is the wrong fix. The function signature shouldn't need to change?

**Comment by rrennick** [comment]
@crstauf Thanks for the PR. On the docs changes, have you seen `null` being explicitly added to PHPDocs as a parameter type in the WP space?

I tested this using the following code against both master and this PR

```
//* Test as_unschedule_action.
add_action( 'init', function() {
	$hook       = 'issue_417';
	$group      = 'as-testing';
	$empty_args = [];
	$test_args  = [ 'id' => rand( 1000, 2000 ) ];

	error_log( 'Empty: ' . as_schedule_single_action( 'tomorrow', $hook, $empty_args, $group ) );
	error_log( 'Random: ' . as_schedule_single_action( 'tomorrow', $hook, $test_args, $group ) );
	error_log( 'Unhook: ' . as_unschedule_action( $hook ) );
	error_log( 'Unhook: ' . as_unschedule_action( $hook ) );
	error_log( 'Unhook: ' . as_unschedule_action( $hook, null, $group ) );
});
```

Results on `master`:
```
[05-Mar-2020 19:50:35 UTC] Empty: 6495
[05-Mar-2020 19:50:35 UTC] Random: 6496
[05-Mar-2020 19:50:35 UTC] Unhook: 6495
[05-Mar-2020 19:50:35 UTC] Unhook: 
[05-Mar-2020 19:50:35 UTC] Unhook: 6496
```

Results on PR:
```
[05-Mar-2020 19:51:06 UTC] Empty: 6497
[05-Mar-2020 19:51:06 UTC] Random: 6498
[05-Mar-2020 19:51:06 UTC] Unhook: 6497
[05-Mar-2020 19:51:06 UTC] Unhook: 6498
[05-Mar-2020 19:51:06 UTC] Unhook:
```
Changing the test code to
```
	error_log( 'Unhook: ' . as_unschedule_action( $hook, $empty_args ) );
	error_log( 'Unhook: ' . as_unschedule_action( $hook, $empty_args ) );
	error_log( 'Unhook: ' . as_unschedule_action( $hook, null, $group ) );
```

Resulted in
```
[05-Mar-2020 19:58:39 UTC] Empty: 6529
[05-Mar-2020 19:58:39 UTC] Random: 6530
[05-Mar-2020 19:58:39 UTC] Unhook: 6529
[05-Mar-2020 19:58:39 UTC] Unhook: 
[05-Mar-2020 19:58:39 UTC] Unhook: 6530
```

Testing shows that you can both unschedule with just the hook and explicitly limit the unschedule to an action with empty args.

This PR looks good but it will be a bit before it gets merged for v 3.2.0.

**Comment by crstauf** [comment]
> have you seen `null` being explicitly added to PHPDocs as a parameter type in the WP space?

Did a search of WP core with this regex, `param .*null.*`, and there are several results.

**Comment by leewillis77** [comment]
Aside from my earlier comment about the proposed fix. Isn't this change unnecessary anyway since you can already use `as_unschedule_all_actions()` to unscheduled actions by hook name only?

**Comment by rrennick** [comment]
@leewillis77 Having an alternative does make this PR less urgent but it does address these things:

- Function behaviour matches the PHPDocs / default parameters
- Allows explicit targeting of actions with an empty `$args` array

The reason I haven't included this PR in the bugfix releases is that it's not a regression in the 3.X versions.

**Comment by rrennick** [comment]
@crstauf Thanks for the contribution. This still looks good other than the merge conflicts. I'll merge once those are fixed up.

**Comment by crstauf** [comment]
> other than the merge conflicts

@rrennick `version_3_2_0` merged in and conflicts resolved.

**Review by rrennick — APPROVED** [review]
@crstauf Thanks again. Looks great.

**Pull request merged**
