### PR TITLE
PHPCS fixes: `WordPress` and `WooCommerce`

### PR DESCRIPTION
**Pull request by crstauf**
Eliminates most smells from the `WordPress` and `WooCommerce` standards.

See #971.

### CODE REVIEW

**Comment by crstauf** [comment]
@barryhughes Why would these changes cause the unit tests to fail?

**Comment by barryhughes** [comment]
@crstauf I haven't really had time to look at this, but I wonder if you could isolate it to a specific commit by performing a git bisect?

**Comment by crstauf** [comment]
Okay, will give that a try.

**Comment by crstauf** [comment]
Gah, Local's lack of support for PHPUnit strikes again.

**Comment by crstauf** [comment]
@barryhughes Stalled.

**Pull request closed without merging**
