### PR TITLE
Add a way to bulk delete actions by hook

### LINKED ISSUE #394: Add admin a way to bulk delete actions, ideally by hook not just displayed on a page
We see intermittent cases of the Action Scheduler queue becoming clogged. The reasons for this differ, e.g. one plugin was _enqueuing an action on every page load_ 🙈, but the symptom is always the same - a large number of actions in the queue that shouldn't be there, and that need to be removed.

To unclog the queue, a site needs to just wait, or run [a SQL query directly on the DB](https://nickgreen.info/clearing-a-clogged-action-scheduler-queue-woocommerce/).

To avoid having to manually run SQL, we could add a UI for bulk deleting actions based on a hook. Or better yet, we could just add a backdoor, like a `$_GET` param on an admin page, to bulk delete actions by a certain hook as needed.

### PR DESCRIPTION
**Pull request by crstauf**
Closes #394.

### CODE REVIEW

**Comment by crstauf** [comment]
Travis CI indicates all checks have completed, but GitHub seems to think the build is in progress.

**Comment by crstauf** [comment]
@rrennick @thenbrent This PR is ready for review.

**Comment by rrennick** [comment]
@crstauf This has conflicts that need resolved.

**Comment by crstauf** [comment]
@rrennick `version_3_2_0` merged in and conflict resolved.

**Comment by rrennick** [comment]
@crstauf Can you update the description on this to describe the purpose of the new code? The current admin screen already has a bulk delete feature so it's not clear why this is being added.

**Comment by crstauf** [comment]
@rrennick I'll need to defer to @thenbrent, as I created this PR at his request in #394.

**Comment by thenbrent** [comment]
@rrennick let me know if #394 doesn't provide enough context. That was raised after seeing the scheduled webhook issues last year.

**Comment by rrennick** [comment]
@crstauf Thanks for submitting the PR. Closing this with the explanation below.

In investigating an issue in another plugin I've looked at a couple installs that had 25+ million actions that had been created. Deleting at a rate of 5000 / minute requires about 4 days to purge off 25M actions. New features and changes need to be scalable to support high volume sites.

Secondly, Action Scheduler is used in approximately 8 - 10 million installs and non programatic features should have an interface that can be documented for non-technical users.

**Pull request closed without merging**
