### PR TITLE
WP CLI: 'version' command

### PR DESCRIPTION
**Pull request by crstauf**
The [second commit of `version` command](https://github.com/crstauf/action-scheduler/commit/5750802b0bfa4dca7ba4750551907af9ce60ba55) may not be wanted, as it makes some changes to `ActionScheduler_Versions` class; I went ahead and built it, as I see benefit, but also recognize it may not be wanted. Please let me know, and I can revert before merging.

Screenshot of `version` command output:

Screen Shot 2019-03-27 at 12 40 35 AM

### CODE REVIEW

**Comment by thenbrent** [comment]
I'll leave review of this up to @JPry. Just a quick not to say I've changed the base branch on this to `release/2.3.0`, as it will go out with that version.

**Comment by rrennick** [comment]
Updated the base for this PR to `version_3_1_0`.

**Comment by rrennick** [comment]
> as it makes some changes to ActionScheduler_Versions class;

@crstauf You can get the latest version with `ActionScheduler_Versions::latest_version()`. The CLI command won't be registered if `latest_version()` returns `false`. 

If you feel there would be improvement in the code organization in WP CLI commands, that can be submitted as a separate PR. Protected functions can be used in derived classes and cannot be removed from non-`final` classes without going through a deprecation process.

**Comment by crstauf** [comment]
> improvement in the code organization in WP CLI commands

@rrennick #280 is my proposal.

Once that's merged in, I'll go through and update all the branches for additional commands.

**Comment by rrennick** [comment]
@crstauf How did you create this screenshot:

Screen Shot 2019-03-27 at 12 40 35 AM

In AS version 2.2.1 (or 3.1.6) there is a check to see whether the [`action_scheduler_register_X_dot_X_dot_X` function already exists](https://github.com/woocommerce/action-scheduler/blob/master/action-scheduler.php#L28). Only the first instance of the main plugin file of a particular version runs any code inside the main `if` block. The `--all` would only list the first instance of each version.

This PR also makes several changes that are unrelated to the `version` subcommand. I created a branch with a `version` subcommand with a `--which` flag - https://github.com/woocommerce/action-scheduler/compare/version_3_2_0...add/version-command?expand=1. Do you have any objections with closing this PR and using the simplified approach in that branch?

**Comment by crstauf** [comment]
@rrennick This PR makes [adjustments to `ActionScheduler_Versions`](https://github.com/crstauf/action-scheduler/commit/5750802b0bfa4dca7ba4750551907af9ce60ba55) and collects all the different versions that are available on the WordPress install, and the `version` command lists them and their source.

> Do you have any objections with closing this PR

I do not; I mention in the opening comment that I see benefit to listing out all versions, but understand it may not be wanted and/or create complexity.

**Comment by rrennick** [comment]
> This PR makes adjustments to ActionScheduler_Versions

It would only affect this (and future) versions of AS. Any existing versions would not have these changes effectively rendering the `--all` unreliable for an indefinite period of time into the future.

> I do not

Thanks, I'll close this and create a PR later today.

**Pull request closed without merging**
